### ISSUE TITLE
параметри рядка запиту

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/phones-app#2]
https://github.com/DenisPitsul/phones-app/blob/5ca8072b57ac9abc3080ddda742daf443be79f26/client/src/api/index.js#L12-L15
- якщо користуватися [query-string](https://www.npmjs.com/package/query-string), то `undefined` і так відсікатимуться і не будуть присутні у запиті, тоді перевірки можна не робити. Так запити будуть лаконічнішими і в підтримці легшими

**Comment by DenisPitsul** [comment]
Refactored in commit:
https://github.com/DenisPitsul/phones-app/commit/c41dccc9f28417e9680f953aaf14f92dd16f321b

**Comment by pecourses** [comment]
- про всяк випадок зазначу, що в реальності `results` також приходитиме в параметрах і код буде ще лаконічніший 🙂
